function [perm, pol] = GetRotsCommon(FLAG,fam,CATA,datapath,sft2,sft3)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function is to get the rotation parameters of the permanent and
% polaris stations, including split correction and optimal polarization
% angles, according to fam number and centroid shifts based on Chao's new
% calculations, calc_rots_norespv3
%
% --Recommended! This is integrated to accept different detector type (FLAG), 
%   different fam (fam), different path of data (datapath), different 
%   location of centroid (sft2, sft3). 
% --For PGC trio, if fam is 002, allows CATA options to use 'fixed' results 
%   from Yajun/Allan; Or, computed 'old' rots from old days and old LFE 
%   catalog; Or, the computed 'new' rots from new days and new LFE catalog,
%   which has a distinguished suffix in filename. 
%   All other fams use computed rots from new days and new LFE catalog,
%   but they don't have a difference in suffix in filename.
% --For LZB trio, all fams use the computed rots from new days and
%   new LFE catalog.
%
%
% --'GetRots' now uses hardcoded params from Yajun/Allan for PGC fam 002;
%   'GetRotsPGC' deals with computed results of other fams than 002 using 
%     PGC from 'calc_rots_norespv??';
%   'GetRotsPGC002' specifically deals with computed results of fam 002
%     using PGC but base on different LFE catalogs to see the difference
%   'GetRotsChao' can deal with all fams using the TWKB trio, and fams other
%     than 002 using the PGC trio, depending on FLAG

%   
%
%
% Modified by Chao Song, chaosong@princeton.edu
% First created date:   2021/10/20
% Last modified date:   2021/10/21
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%% Meanning of each column in PERMROTS/POLROTS %%%%%%%%
%%% 1. offset in samples between fast/slow direction, unit in 40 sps
%%% 2. rotation angle to get fast/slow direction
%%% 3. rotation angle to maximize the energy/particle motion/polarization
%%% 4. offset in samples between the arrival times at different stations, unit in 40 sps
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if isequal(FLAG,'PGC')
  if isequal(fam,'002')
    if isequal(CATA,'fixed')
      %%%%%%%%%%%% VERSION 1, FROM YAJUN %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
      %%% Permanent stations rotation angles, NAMES can be found in Rubin &
      %%% Armbruster 2013, Armbruster et al., 2014
      perm=[0 90 32 0;  %PGC , Yajun's "0" changed to 90.  Don't think that matters, if no splitting.
            0 90 54 9]; %LZB

      %%% POLARIS stations rotation angles
      pol=[6 85 33 86+sft2;  %SSIB from Yajun          
           0 90 39 20+sft3;  %SILB
           0 90  7 -4;  %KLNB
           4 70 48 -26; %MGCB
           4 75 38 -5]; %TWKB
      %%%%%%%%%%%% VERSION 1, FROM YAJUN %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    elseif isequal(CATA,'old')  
      %%%%%%%%%%%% VERSION 2, FROM OLD DAYS AND OLD CATALOG %%%%%%%%%%%%%%%%%
      lo = 0.5;
      hi = 6.5;
      sps = 40;
      bef = 25;
      aft = 35;
      nsta = 7;
      PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
                      num2str(aft),'PGC');
      ROTS = load(strcat(datapath, '/split_chao/pgctrio/',...
                  PREFIX,'_',num2str(sps),'sps',num2str(nsta),'stas_oldcat'));

      % the order in ROTS from the result file generated by calc_rots_noresp
      % is PGC,SSIB,SILB,LZB,TWKB,MGCB,KLNB,
      % make sure the order accords with the PERMSTA and POLSTA
      perm(1,:) =  ROTS(1,:);
      perm(2,:) =  ROTS(4,:);
      perm(2,4) = perm(2,4)+sft2;    % LZB (sta #2) plus centroid shift 2

      pol(1:2,:) =  ROTS(2:3,:);
      pol(3,:) =  ROTS(7,:);
      pol(4,:) =  ROTS(6,:);
      pol(5,:) =  ROTS(5,:);      % TWKB should be the sta #1

      pol(4,4) = pol(4,4)+sft3;   % MGCB (sta #3) plus centroid shift 3
      %%%%%%%%%%%% VERSION 2, FROM OLD DAYS AND OLD CATALOG %%%%%%%%%%%%%%%%%
    
    elseif isequal(CATA,'new')
      %%%%%%%%%%%% VERSION 3, FROM AUTOMATIC DAYS AND NEW CATALOG %%%%%%%%%%%%%%%%%
      lo = 0.5;
      hi = 6.5;
      sps = 40;
      bef = 25;
      aft = 35;
      nsta = 7;
      PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
                      num2str(aft),'PGC');
      ROTS = load(strcat(datapath, '/split_chao/pgctrio/',...
                  PREFIX,'_',num2str(sps),'sps',num2str(nsta),'stas_newcat'));

      % the order in ROTS from the result file generated by calc_rots_noresp
      % is PGC,SSIB,SILB,LZB,TWKB,MGCB,KLNB,
      % make sure the order accords with the PERMSTA and POLSTA
      perm(1,:) =  ROTS(1,:);
      perm(2,:) =  ROTS(4,:);
      perm(2,4) = perm(2,4)+sft2;    % LZB (sta #2) plus centroid shift 2

      pol(1:2,:) =  ROTS(2:3,:);
      pol(3,:) =  ROTS(7,:);
      pol(4,:) =  ROTS(6,:);
      pol(5,:) =  ROTS(5,:);      % TWKB should be the sta #1

      pol(4,4) = pol(4,4)+sft3;   % MGCB (sta #3) plus centroid shift 3
      %%%%%%%%%%%% VERSION 3, FROM AUTOMATIC DAYS AND NEW CATALOG %%%%%%%%%%%%%%%%%
    end

  elseif isequal(fam,'068')   % 068 seems to be a fam only in the OLD LFE catalog 
        
    perm=[0  0  0  0;  %PGC
          8 65  6 -8]; %LZB
    pol=[0  0  0  0+sft2;  %SSIB 
         0  0  0  0+sft3;  %SILB
         2 50 25  0;  %KLNB (erroneous delay w.r.t. TWKB last column)     % w.r.t. with respect to
         5 65 41 -1;  %MGCB
         4 60 14  0]; %TWKB
  
  else
%   elseif isequal(fam,'243') || isequal(fam,'240')
    lo = 0.5;
    hi = 6.5;
    sps = 40;
    bef = 25;
    aft = 35;
    nsta = 7;
    PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
      num2str(aft),'PGC');
    ROTS = load(strcat(datapath, '/split_chao/pgctrio/',...
      PREFIX,'_',num2str(sps),'sps',num2str(nsta),'stas_newcat'));
    
    % the order in ROTS from the result file generated by calc_rots_noresp
    % is PGC,SSIB,SILB,LZB,TWKB,MGCB,KLNB,
    % make sure the order accords with the PERMSTA and POLSTA
    perm(1,:) =  ROTS(1,:);
    perm(2,:) =  ROTS(4,:);
    perm(2,4) = perm(2,4)+sft2;    % LZB (sta #2) plus centroid shift 2
    
    pol(1:2,:) =  ROTS(2:3,:);
    pol(3,:) =  ROTS(7,:);
    pol(4,:) =  ROTS(6,:);
    pol(5,:) =  ROTS(5,:);      % TWKB should be the sta #1
    
    pol(4,4) = pol(4,4)+sft3;   % MGCB (sta #3) plus centroid shift 3
    % keyboard
  end
  
elseif isequal(FLAG,'TWKB') || isequal(FLAG,'LZB')
% else
  lo = 0.5;
  hi = 6.5;
  sps = 40;
  bef = 25;
  aft = 35;
  nsta = 7;
  famp1 = ['002';'043';'141';'047';'010';'099';'017';'001';'019';'021';'045';'076';'176';'015';...
    '158';'231';'234';'006'];
  famp2 = ['144';'068';'125';'147'];
  if ismember(fam,famp1,'rows')
    PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
      num2str(aft),'LZB');
  elseif ismember(fam,famp2,'rows')
    PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
      num2str(aft),'TWKB');
  end
  ROTS = load(strcat(datapath, '/split_chao/lzbtrio/',...
    PREFIX,'_',num2str(sps),'sps',num2str(nsta),'stas'));

  % the order in ROTS from the result file generated by calc_rots_noresp
  % is PGC,SSIB,SILB,LZB,TWKB,MGCB,KLNB,
  % make sure the order accords with the PERMSTA and POLSTA
  perm(1,:) =  ROTS(1,:);
  perm(2,:) =  ROTS(4,:);
  perm(2,4) = perm(2,4)+sft2;    % LZB (sta #2) plus centroid shift 2

  pol(1:2,:) =  ROTS(2:3,:);
  pol(3,:) =  ROTS(7,:);
  pol(4,:) =  ROTS(6,:);
  pol(5,:) =  ROTS(5,:);      % TWKB should be the sta #1

  pol(4,4) = pol(4,4)+sft3;   % MGCB (sta #3) plus centroid shift 3
  % keyboard
        
end

% keyboard