% Your data...
figure
x = ft;

y = x.^2;
% Now make the 'line' (actually a surface)...
z = zeros(size(x));
S = surface([x;x],[y;y],[z;z],...
            'facecol','no',...
            'edgecol','interp',...
            'linew',2,...
            'edgealpha',.2,...
            'edgecolor','b');
holon on