function [perm, pol] = GetRotsPGC002(CATA,sft2,sft3)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function is to get the rotation parameters of the permanent and
% polaris stations, including split correction and optimal polarization
% angles, according to fam number and centroid shifts
% 
% --Only for fam 002 using PGC trio, computed, instead of hardcoded known
%   parameters. Allowing options for different LFE catalogs (CATA, separated
%   or whole file)
% --This is basically to move the 2nd and 3rd options in 'GetRots' here, as
%   'GetRots' now uses hardcoded params for PGC fam 002; 'GetRotsPGC' deals
%   with computed results of other fams using PGC; 'GetRotsPGC002' deals with
%   computed results of fam 002 using PGC but base on different LFE catalogs
%   to see the difference
% 
%
% Modified by Chao Song, chaosong@princeton.edu
% First created date:   2019/06/25
% Last modified date:   2021/10/21
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

fam = '002';

    %%%%%%%% Meanning of each column in PERMROTS/POLROTS %%%%%%%%
    %%% 1. offset in samples between fast/slow direction, unit in 40 sps
    %%% 2. rotation angle to get fast/slow direction
    %%% 3. rotation angle to maximize the energy/particle motion/polarization
    %%% 4. offset in samples between the arrival times at different stations, unit in 40 sps
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if isequal(CATA,'old')    
    %%%%%%%%%%%% VERSION 2, FROM OLD DAYS AND OLD CATALOG %%%%%%%%%%%%%%%%%
    lo = 0.5;
    hi = 6.5;
    sps = 40;
    bef = 25;
    aft = 35;
    nsta = 7;
    PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
                    num2str(aft),'PGC');
    ROTS = load(strcat('/home/data2/chaosong/matlab/allan/data-no-resp/split_chao/pgctrio/',...
                PREFIX,'_',num2str(sps),'sps',num2str(nsta),'stas_oldcat'));
    
    % the order in ROTS from the result file generated by calc_rots_noresp
    % is PGC,SSIB,SILB,LZB,TWKB,MGCB,KLNB,
    % make sure the order accords with the PERMSTA and POLSTA
    perm(1,:) =  ROTS(1,:);
    perm(2,:) =  ROTS(4,:);
    perm(2,4) = perm(2,4)+sft2;    % LZB (sta #2) plus centroid shift 2
    
    pol(1:2,:) =  ROTS(2:3,:);
    pol(3,:) =  ROTS(7,:);
    pol(4,:) =  ROTS(6,:);
    pol(5,:) =  ROTS(5,:);      % TWKB should be the sta #1
    
    pol(4,4) = pol(4,4)+sft3;   % MGCB (sta #3) plus centroid shift 3
    %%%%%%%%%%%% VERSION 2, FROM OLD DAYS AND OLD CATALOG %%%%%%%%%%%%%%%%%
 
elseif isequal(CATA,'new')    
    %%%%%%%%%%%% VERSION 3, FROM AUTOMATIC DAYS AND NEW CATALOG %%%%%%%%%%%%%%%%%
    lo = 0.5;
    hi = 6.5;
    sps = 40;
    bef = 25;
    aft = 35;
    nsta = 7;
    PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
                    num2str(aft),'PGC');
    ROTS = load(strcat('/home/data2/chaosong/matlab/allan/data-no-resp/split_chao/pgctrio/',...
                PREFIX,'_',num2str(sps),'sps',num2str(nsta),'stas_newcat'));
    
    % the order in ROTS from the result file generated by calc_rots_noresp
    % is PGC,SSIB,SILB,LZB,TWKB,MGCB,KLNB,
    % make sure the order accords with the PERMSTA and POLSTA
    perm(1,:) =  ROTS(1,:);
    perm(2,:) =  ROTS(4,:);
    perm(2,4) = perm(2,4)+sft2;    % LZB (sta #2) plus centroid shift 2
    
    pol(1:2,:) =  ROTS(2:3,:);
    pol(3,:) =  ROTS(7,:);
    pol(4,:) =  ROTS(6,:);
    pol(5,:) =  ROTS(5,:);      % TWKB should be the sta #1
    
    pol(4,4) = pol(4,4)+sft3;   % MGCB (sta #3) plus centroid shift 3
    %%%%%%%%%%%% VERSION 3, FROM AUTOMATIC DAYS AND NEW CATALOG %%%%%%%%%%%%%%%%%
    
end


