function [perm, pol] = GetRotsPGC(fam,sft2,sft3)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function is to get the rotation parameters of the permanent and
% polaris stations, including split correction and optimal polarization
% angles, according to fam number and centroid shifts
% 
%   For PGC trio; all the other fams than 002; using the combined lfe cataog
%   /BOSTOCK/total_mag_detect_0000_cull_NEW.txt to automatically find the days
%   that has sufficient number of lfes to stack, and stack based on the timings
%   of lfes in the new catalog
%   
%   2021/10/21: recommend to use 'GetRotsCommon' that allows the FLAG indicating
%   the type of the detector
%   2022/02/09: This function is the same as 'GetRotsChao' using FLAG=='PGC'
%
% Modified by Chao Song, chaosong@princeton.edu
% First created date:   2021/06/30
% Last modified date:   2022/02/09
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%% Meanning of each column in PERMROTS/POLROTS %%%%%%%%
%%% 1. offset in samples between fast/slow direction, unit in 40 sps
%%% 2. rotation angle to get fast/slow direction
%%% 3. rotation angle to maximize the energy/particle motion/polarization
%%% 4. offset in samples between the arrival times at different stations, unit in 40 sps
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if strcmp(fam, '002')
  warning("You should not use 'GetRotsPGC' for fam 002");
end

lo = 0.5;
hi = 6.5;
sps = 40;
bef = 25;
aft = 35;
nsta = 7;
PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
    num2str(aft),'PGC');
ROTS = load(strcat('/home/data2/chaosong/matlab/allan/data-no-resp/split_chao/pgctrio/',...
    PREFIX,'_',num2str(sps),'sps',num2str(nsta),'stas'));

% the order in ROTS from the result file generated by calc_rots_noresp
% is PGC,SSIB,SILB,LZB,TWKB,MGCB,KLNB,
% make sure the order accords with the PERMSTA and POLSTA
perm(1,:) =  ROTS(1,:);
perm(2,:) =  ROTS(4,:);
perm(2,4) = perm(2,4)+sft2;    % LZB (sta #2) plus centroid shift 2

pol(1:2,:) =  ROTS(2:3,:);
pol(3,:) =  ROTS(7,:);
pol(4,:) =  ROTS(6,:);
pol(5,:) =  ROTS(5,:);      % TWKB should be the sta #1

pol(4,4) = pol(4,4)+sft3;   % MGCB (sta #3) plus centroid shift 3




