function [perm, pol] = GetRots(fam,sft2,sft3)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function is to get the rotation parameters of the permanent and
% polaris stations, including split correction and optimal polarization
% angles, according to fam number and centroid shifts
% 
%  	Only for fam 002 using PGC trio!!!
%
%   2021/10/21: recommend to use 'GetRotsCommon' that allows the FLAG indicating
%   the type of the detector% 
%
% Modified by Chao Song, chaosong@princeton.edu
% First created date:   2019/06/25
% Last modified date:   2021/10/21
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if isequal(fam,'002')
    
    %%%%%%%% Meanning of each column in PERMROTS/POLROTS %%%%%%%%
    %%% 1. offset in samples between fast/slow direction, unit in 40 sps
    %%% 2. rotation angle to get fast/slow direction
    %%% 3. rotation angle to maximize the energy/particle motion/polarization
    %%% 4. offset in samples between the arrival times at different stations, unit in 40 sps
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    %%%%%%%%%%%% VERSION 1, FROM YAJUN %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%% Permanent stations rotation angles, NAMES can be found in Rubin &
    %%% Armbruster 2013, Armbruster et al., 2014
    perm=[0 90 32 0;  %PGC , Yajun's "0" changed to 90.  Don't think that matters, if no splitting.
          0 90 54 9]; %LZB
          
    %%% POLARIS stations rotation angles
    pol=[6 85 33 86+sft2;  %SSIB from Yajun          
         0 90 39 20+sft3;  %SILB
         0 90  7 -4;  %KLNB
         4 70 48 -26; %MGCB
         4 75 38 -5]; %TWKB
    %%%%%%%%%%%% VERSION 1, FROM YAJUN %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
%     %%%%%%%%%%%% VERSION 2, FROM OLD DAYS AND OLD CATALOG %%%%%%%%%%%%%%%%%
%     lo = 0.5;
%     hi = 6.5;
%     sps = 40;
%     bef = 25;
%     aft = 35;
%     nsta = 7;
%     PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
%                     num2str(aft),'PGC');
%     ROTS = load(strcat('/home/data2/chaosong/matlab/allan/data-no-resp/split_chao/pgctrio/',...
%                 PREFIX,'_',num2str(sps),'sps',num2str(nsta),'stas_oldcat'));
%     
%     % the order in ROTS from the result file generated by calc_rots_noresp
%     % is PGC,SSIB,SILB,LZB,TWKB,MGCB,KLNB,
%     % make sure the order accords with the PERMSTA and POLSTA
%     perm(1,:) =  ROTS(1,:);
%     perm(2,:) =  ROTS(4,:);
%     perm(2,4) = perm(2,4)+sft2;    % LZB (sta #2) plus centroid shift 2
%     
%     pol(1:2,:) =  ROTS(2:3,:);
%     pol(3,:) =  ROTS(7,:);
%     pol(4,:) =  ROTS(6,:);
%     pol(5,:) =  ROTS(5,:);      % TWKB should be the sta #1
%     
%     pol(4,4) = pol(4,4)+sft3;   % MGCB (sta #3) plus centroid shift 3
%     %%%%%%%%%%%% VERSION 2, FROM OLD DAYS AND OLD CATALOG %%%%%%%%%%%%%%%%%
 
%     %%%%%%%%%%%% VERSION 3, FROM AUTOMATIC DAYS AND NEW CATALOG %%%%%%%%%%%%%%%%%
%     lo = 0.5;
%     hi = 6.5;
%     sps = 40;
%     bef = 25;
%     aft = 35;
%     nsta = 7;
%     PREFIX = strcat(fam,'rot_para',num2str(lo),'-',num2str(hi),'_',num2str(bef),'_',...
%                     num2str(aft),'PGC');
%     ROTS = load(strcat('/home/data2/chaosong/matlab/allan/data-no-resp/split_chao/pgctrio/',...
%                 PREFIX,'_',num2str(sps),'sps',num2str(nsta),'stas_newcat'));
%     
%     % the order in ROTS from the result file generated by calc_rots_noresp
%     % is PGC,SSIB,SILB,LZB,TWKB,MGCB,KLNB,
%     % make sure the order accords with the PERMSTA and POLSTA
%     perm(1,:) =  ROTS(1,:);
%     perm(2,:) =  ROTS(4,:);
%     perm(2,4) = perm(2,4)+sft2;    % LZB (sta #2) plus centroid shift 2
%     
%     pol(1:2,:) =  ROTS(2:3,:);
%     pol(3,:) =  ROTS(7,:);
%     pol(4,:) =  ROTS(6,:);
%     pol(5,:) =  ROTS(5,:);      % TWKB should be the sta #1
%     
%     pol(4,4) = pol(4,4)+sft3;   % MGCB (sta #3) plus centroid shift 3
%     %%%%%%%%%%%% VERSION 3, FROM AUTOMATIC DAYS AND NEW CATALOG %%%%%%%%%%%%%%%%%

% elseif isequal(fam,'068')
%         
%     perm=[0  0  0  0;  %PGC
%           8 65  6 -8]; %LZB
%     pol=[0  0  0  0+sft2;  %SSIB 
%          0  0  0  0+sft3;  %SILB
%          2 50 25  0;  %KLNB (erroneous delay w.r.t. TWKB last column)     % w.r.t. with respect to
%          5 65 41 -1;  %MGCB
%          4 60 14  0]; %TWKB

else
    warning("You should not use 'GetRots' for fams other than 002 with PGC trio");
end







